### PR TITLE
Added Code of Conduct, renamed Swift X to Open Swift in the Readme

### PR DESCRIPTION
**Pull request by czechboy0**
I think the size of Open Swift justifies having a set of rules that define encouraged behavior. I chose Contributor Covenant's Code of Conduct, as that's the current industry standard and to me sums up the rights and responsibilities of our community when interacting with one another pretty well. Happy to discuss any alternatives.

It would be great if I could get everyone's 👍 on this PR, so that we make sure that everyone is aware of the CoC being added, and it'd be great if you could give it a read. After all, even as we grow we want to make sure we're a friendly and welcoming community to everyone without discrimination and that we're serious about enforcing the rules in the CoC below. 😊

### CODE REVIEW

**Comment by LoganWright** [comment]
Looks great 👍 My only suggestion is to include at least one additional point of contact in addition to Paulo.

**Comment by czechboy0** [comment]
Good point, @tannernelson can I add you?

**Comment by tannernelson** [comment]
Sure thing.

**Comment by tannernelson** [comment]
Merging this with 2 votes.

**Pull request merged**
